app = "prototypes"
primary_region = "atl"

[env]
NEXT_PUBLIC_API_URL = "https://grokapi.fly.dev/api"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"