app = 'prototypes'
primary_region = 'atl'


[env]
  NEXT_PUBLIC_API_URL = "https://grokapi.fly.dev/api"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID = "509405291776-3okmqhk0rlhiblo58nso00r5bbho1925.apps.googleusercontent.com"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1